import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/intro',
        'getting-started/installation',
        'getting-started/quick-start',
        'core-concepts/admin',
        'core-concepts/resource-schema',
        'core-concepts/data-providers',
        'core-concepts/auth-providers',
        'core-concepts/translation',
        {
          type: 'category',
          label: 'Tutorial: Building a complete Admin',
          link: {
            type: 'generated-index',
          },
          items: [{ type: 'autogenerated', dirName: 'getting-started/tutorial' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/Admin',
        'reference/ResourceSchema',
        'reference/Settings',
        {
          type: 'category',
          label: 'Fields',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/fields' }],
        },
        {
          type: 'category',
          label: 'Inputs',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/inputs' }],
        },
        {
          type: 'category',
          label: 'List',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/list' }],
        },
        {
          type: 'category',
          label: 'Detail',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/detail' }],
        },
        {
          type: 'category',
          label: 'Forms',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/forms' }],
        },
        {
          type: 'category',
          label: 'Buttons',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/buttons' }],
        },
        {
          type: 'category',
          label: 'Translations',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/translations' }],
        },
        {
          type: 'category',
          label: 'Hooks',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'reference/hooks' }],
        },
      ],
    },
  ],
};

export default sidebars;
