import fakeRestDataProvider from 'ra-data-fakerest';

const data = {
  products: [
    {
      id: 1,
      name: 'Eco-Friendly Water Bottle',
      price: 25.0,
      stock: 150,
      categoryId: 1,
      description: 'Stay hydrated with our BPA-free, eco-friendly water bottle.',
      lastRestocked: '2024-03-01',
      isEcoFriendly: true,
    },
    {
      id: 2,
      name: 'Organic Cotton T-Shirt',
      price: 30.0,
      stock: 200,
      categoryId: 2,
      description: 'A comfortable T-shirt made from 100% organic cotton.',
      lastRestocked: '2024-02-15',
      isEcoFriendly: true,
    },
    {
      id: 3,
      name: 'Bamboo Toothbrush',
      price: 5.5,
      stock: 500,
      categoryId: 1,
      description: 'Sustainable bamboo toothbrush with soft bristles.',
      lastRestocked: '2024-03-05',
      isEcoFriendly: true,
    },
    {
      id: 4,
      name: 'Recycled Paper Notebook',
      price: 12.0,
      stock: 100,
      categoryId: 3,
      description: 'Notebook with pages made from 100% recycled paper.',
      lastRestocked: '2024-01-20',
      isEcoFriendly: true,
    },
    {
      id: 5,
      name: 'Solar Powered Charger',
      price: 45.0,
      stock: 45,
      categoryId: 1,
      description: 'Charge your devices on the go using solar power.',
      lastRestocked: '2024-03-02',
      isEcoFriendly: true,
    },
    {
      id: 6,
      name: 'Hemp Backpack',
      price: 65.0,
      stock: 30,
      categoryId: 2,
      description: 'Durable and spacious backpack made from hemp fiber.',
      lastRestocked: '2024-02-28',
      isEcoFriendly: true,
    },
    {
      id: 7,
      name: 'Glass Food Containers',
      price: 35.0,
      stock: 80,
      categoryId: 1,
      description: 'Set of 5 glass containers with bamboo lids.',
      lastRestocked: '2024-03-06',
      isEcoFriendly: true,
    },
    {
      id: 8,
      name: 'Reclaim Wood Wall Art',
      price: 120.0,
      stock: 10,
      categoryId: 1,
      description: 'Unique wall art piece made from reclaimed barn wood.',
      lastRestocked: '2024-01-15',
      isEcoFriendly: true,
    },
    {
      id: 9,
      name: 'Beeswax Food Wraps',
      price: 18.0,
      stock: 300,
      categoryId: 1,
      description: 'Natural alternative to plastic wrap.',
      lastRestocked: '2024-03-04',
      isEcoFriendly: true,
    },
    {
      id: 10,
      name: 'Wool Dryer Balls',
      price: 15.0,
      stock: 250,
      categoryId: 1,
      description: 'Shorten drying time and soften clothes naturally.',
      lastRestocked: '2024-02-20',
      isEcoFriendly: true,
    },
    {
      id: 11,
      name: 'Cork Yoga Mat',
      price: 85.0,
      stock: 40,
      categoryId: 1,
      description: 'Natural cork surface for superior grip.',
      lastRestocked: '2024-03-01',
      isEcoFriendly: true,
    },
    {
      id: 12,
      name: 'Linen Bed Sheets',
      price: 150.0,
      stock: 25,
      categoryId: 1,
      description: 'Breathable and soft 100% linen sheets.',
      lastRestocked: '2024-02-10',
      isEcoFriendly: true,
    },
    {
      id: 13,
      name: 'Bamboo Cutlery Set',
      price: 12.5,
      stock: 400,
      categoryId: 1,
      description: 'Portable reusable cutlery for on-the-go meals.',
      lastRestocked: '2024-03-05',
      isEcoFriendly: true,
    },
    {
      id: 14,
      name: 'Organic Cotton Socks',
      price: 10.0,
      stock: 600,
      categoryId: 2,
      description: 'Comfortable and sustainable everyday socks.',
      lastRestocked: '2024-03-03',
      isEcoFriendly: true,
    },
    {
      id: 15,
      name: 'Recycled Polyester Jacket',
      price: 95.0,
      stock: 15,
      categoryId: 2,
      description: 'Warm jacket made from recycled plastic bottles.',
      lastRestocked: '2024-01-25',
      isEcoFriendly: true,
    },
    {
      id: 16,
      name: 'Hemp Canvas Tote',
      price: 15.0,
      stock: 500,
      categoryId: 2,
      description: 'Heavy-duty tote bag for shopping.',
      lastRestocked: '2024-03-02',
      isEcoFriendly: true,
    },
    {
      id: 17,
      name: 'Recycled Glass Vase',
      price: 28.0,
      stock: 50,
      categoryId: 1,
      description: 'Beautifully crafted vase from 100% recycled glass.',
      lastRestocked: '2024-02-05',
      isEcoFriendly: true,
    },
    {
      id: 18,
      name: 'Plant-Based Phone Case',
      price: 32.0,
      stock: 120,
      categoryId: 1,
      description: 'Compostable phone case made from flax.',
      lastRestocked: '2024-03-01',
      isEcoFriendly: true,
    },
    {
      id: 19,
      name: 'Natural Rubber Yoga Block',
      price: 22.0,
      stock: 90,
      categoryId: 1,
      description: 'Support your practice with eco-friendly rubber.',
      lastRestocked: '2024-02-15',
      isEcoFriendly: true,
    },
    {
      id: 20,
      name: 'Organic Tea Sampler',
      price: 24.0,
      stock: 200,
      categoryId: 1,
      description: 'Selection of finest organic herbal teas.',
      lastRestocked: '2024-03-06',
      isEcoFriendly: true,
    },
  ],
  categories: [
    { id: 1, name: 'Home & Lifestyle' },
    { id: 2, name: 'Apparel' },
    { id: 3, name: 'Stationery' },
  ],
};

export const dataProvider = fakeRestDataProvider(data, true);
